config/routes.rb
Rails.application.routes.draw do
  #devise_for :models
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  resources :products  do
    collection do
      get :download
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resources)
    products_path
  end

  def after_sign_out_path_for(resources)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!
  def index
    if params[:search].present?
      @products = current_user.products.where("brand like (?) AND model like (?) AND ram like (?) AND ext_storage like (?)", "%#{params[:brand]}%", "%#{params[:model]}%", "%#{params[:ram]}%", "%#{params[:ext_storage]}%").order('id DESC').paginate(page: params[:page], per_page: 25)
    else
    @products = current_user.products.order('id DESC').paginate(page: params[:page], per_page: 25 )
      end
  end

  def show
    @product = current_user.products.find_by_id(params[:id])
  end

  def download
    @products = current_user.products
    respond_to do |format|
      format.xlsx
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_products.html.erb
<table class="table">
	<thead class="thead-dark">
		<tr>
			<th>Type</th>
			<th>Name</th>
			<th>Brand</th>
			<th>Color</th>
			<th>Created at</th>
			<th>Action</th>
		</tr>
	</thead>
	<% products.each do |product| %>
		<tr>
			<td><%= product.product_type %></td>
			<td><%= product.name %></td>
			<td><%= product.brand %></td>
			<td><%= product.color %></td>
			<td><%= product.created_at %></td>
			<td><%= link_to "view", product_path(product), class: 'btn btn-block btn-warning'%></td>
		</tr>
	<% end %>
</table>
<%= will_paginate products, renderer: BootstrapPagination::Rails %>

app/views/products/index.html.erb
<h2>Product listing</h2>
<%#= link_to "New Product", new_product_path, class: 'btn btn-success' %>
 <%= link_to "Export products as spreadsheet", download_products_path(format: 'xlsx'), class: "btn btn-danger" %>
        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Filters</a>
        <div class="collapse" id="collapseExample">
          <div class="card card-body">
            <%= form_tag products_path, :method => 'get', class: "form-inline", remote: true do %>
                <%= hidden_field_tag :search, 'YES' %>
                Brand : <%= text_field_tag :brand, params[:brand], class: "form-control mb-2 mr-sm-2"%>
                    Model : <%= text_field_tag :model, params[:model], class: "form-control mb-2 mr-sm-2"%>
                        Ram : <%= text_field_tag :ram, params[:ram], class: "form-control mb-2 mr-sm-2"%>
                            Storage: <%= text_field_tag :ext_storage, params[:ext_storage], class: "form-control mb-2 mr-sm-2"%>
                                <%= submit_tag "Search", class: 'btn btn-primary mb-2' %>
                                <% end %>
                                </div>
                                </div>
                                <hr/>
                                <div id="product-list">
                                  <%= render partial: 'products', locals:{products: @products}%>
                                </div>

app/views/products/index.js.erb
$("#product-list").html("<%= escape_javascript(render('products/products', products: @products )) %>")

app/views/products/show.html.erb
<div class="card">
	<div class="card-body">
		<h2 class="card-title">Product information</h2>
		<p class="card-text"> Type : <%= @product.product_type %></p>
		<p class="card-text"> Name : <%= @product.name %></p>
		<p class="card-text"> Brand : <%= @product.brand %></p>
		<p class="card-text"> color : <%= @product.color %></p>
		<p class="card-text"> Year : <%= @product.year %></p>
		<p class="card-text"> Ram : <%= @product.ram %></p>
		<p class="card-text"> External Storage : <%= @product.ext_storage %></p>
		<%= link_to "Back", products_path, class: 'btn btn-default card-link'%>
	</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>